### ISSUE TITLE
Bug: Upload of a new file doesn't allow the user to save

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#497] opened 2023-12-18 08:42 UTC
I tried to add a new file to the Event at the following link:
https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/EventShort/0e2082df-78f3-4ddd-b49b-e4f356385d2a#files
Once i clicked on the `Save & next` button nothing happened.

To replicate the problem:

1. Open the event: https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/EventShort/0e2082df-78f3-4ddd-b49b-e4f356385d2a#files
2. go to Edit view
3. click on `Files`
4. upload a new file
5. add Document Name
6. click on `Save & next`

The problem appears even if no or all Document Name are set.

In the Console I get the following error message: ```index-mNqr6iQp.js:1 SyntaxError: "undefined" is not valid JSON```

More detail can be seen in the screenshot below:

![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/3203bee4-87f8-49fd-9462-d9b4d8449d9f)

**Comment by gappc** [comment] 2024-01-14 15:54
@a-crea I found the culprit in the [EventDocumentCell component](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/development/databrowser/src/domain/cellComponents/components/cells/eventDocumentCell/EventDocumentCell.vue#L40).

The bug was introduced with the PR #482 for mobility support, the reason for the problem is, that the language is passed as vue Ref instead of using the language value. PR #516 should fix the problem.

Please check if PR #516 works for you and let me know if you have further questions.

**Comment by a-crea** [comment] 2024-01-19 17:01
@gappc Fixed with #516 :)

**Closed** 2024-01-23 16:08 UTC
Labels: bug
