### ISSUE TITLE
As an Open Data Hub News Editor I want to program the push notification in a future moment, to better plan the NOI App notifications

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#545] opened 2024-03-12 12:00 UTC
Thi issue is a nice to have funtionality we could implementa and it is related to the issue #534

**Comment by gappc** [comment] 2024-04-14 16:04
@sseppi is this issue a duplicate of #554?

**Comment by sseppi** [comment] 2024-04-15 08:43
@gappc yes, sorry I close this one since there are mote information in the #554 issue.

**Closed** 2024-04-23 16:55 UTC
