### ISSUE TITLE
As an Open Data Hub manager I want an extended version of the Metadata API, to manage all the metadata I need

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#332] opened 2023-03-27 12:53 UTC
Here follows a list of information that we should consider to manage in the metadata:
- Dataset name
- Data set description
- Key words/Tags
- List of sources (auto-generated)
- License list/Availability of data (auto-generated)
- Number of available record (auto-generated)
- Output type 
- API version 
- API link 
- Swagger link
- contact email
- links to documentation (each link must have: title, short description and link)
  - video tutorial
  - wiki pages
  - etc.
- snippet code
- web component link for the preview preview (if available)
- created (date of the first valid data) (auto-generated)
- related content
- related dataset

All (auto-generated) should be generated automatically by the system.

**N.B.** by using this feature the Open Data Hub - Data Browser manager I want the have the possibility create more datasets starting from an original Data sets

**Comment by mrabans** [comment] 2023-04-04 09:41
Could this be a possible structure? https://schema.org/Dataset

**Comment by mrabans** [comment] 2023-04-04 09:56
Some work Google has done on this end:

https://www.blog.google/products/search/making-it-easier-discover-datasets/

https://developers.google.com/search/docs/appearance/structured-data/dataset

https://datasetsearch.research.google.com/

**Comment by gappc** [comment] 2023-04-04 10:54
@mrabans I didn't look into details of the schema.org definition but I really like the idea of relying on existent schemas (e.g. from schema.org) and I think it would be the right direction to look / go forward. The reasons are:

- well defined schemas
- compatibility with existing tools (schema.org is well established)
- should be easier to integrate / communicate with other parties

At the moment I don't have enough knowledge on how to proceed with the integration and what possible issues could arise, but if there is demand, I could take a look into it.

**Comment by gappc** [comment] 2023-04-20 13:37
@sseppi https://github.com/noi-techpark/it.bz.opendatahub.databrowser/issues/329 seems to be a duplicate of this issue

There are now 4 issues with the same topic (seem to be duplicates): #329, #330, #331 and this one. Please close duplicate issues

**Comment by sseppi** [comment] 2023-04-20 15:54
Since this issue seems to be the one with active conversation, I will close all other issue that seems to be a duplicate.

**Comment by gappc** [comment] 2024-01-09 09:26
@sseppi is this issue still relevant?

**Comment by sseppi** [comment] 2024-01-09 16:52
@mrabans what about closing this issue and shift the discussion about future improvement and extensions of the Metadata API in a dedicated discussion?

**Comment by mrabans** [comment] 2024-01-09 17:44
@sseppi yes, let's close it

**Closed** 2024-01-10 08:32 UTC
