### ISSUE TITLE
As an Open Data Hub manager I want an extended version of the Metadata API, to manage all the metadata I need

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#331] opened 2023-03-27 12:52 UTC

**Comment by gappc** [comment] 2023-04-20 13:36
@sseppi duplicate of https://github.com/noi-techpark/it.bz.opendatahub.databrowser/issues/329 ?

**Closed** 2023-04-20 15:53 UTC
